/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScanRouteImport } from './routes/_app.scan'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMembersRouteImport } from './routes/_app.members'
import { Route as AppLoansRouteImport } from './routes/_app.loans'
import { Route as AppGenresRouteImport } from './routes/_app.genres'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBooksRouteImport } from './routes/_app.books'
import { Route as AppBookCopiesRouteImport } from './routes/_app.book-copies'
import { Route as AppAuthorsRouteImport } from './routes/_app.authors'
import { Route as AppMembersIdRouteImport } from './routes/_app.members.$id'
import { Route as AppBooksIdRouteImport } from './routes/_app.books.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppGenresRoute = AppGenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksRoute = AppBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AppRoute,
} as any)
const AppBookCopiesRoute = AppBookCopiesRouteImport.update({
  id: '/book-copies',
  path: '/book-copies',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthorsRoute = AppAuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersIdRoute = AppMembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMembersRoute,
} as any)
const AppBooksIdRoute = AppBooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/authors': typeof AppAuthorsRoute
  '/book-copies': typeof AppBookCopiesRoute
  '/books': typeof AppBooksRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/genres': typeof AppGenresRoute
  '/loans': typeof AppLoansRoute
  '/members': typeof AppMembersRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/books/$id': typeof AppBooksIdRoute
  '/members/$id': typeof AppMembersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/authors': typeof AppAuthorsRoute
  '/book-copies': typeof AppBookCopiesRoute
  '/books': typeof AppBooksRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/genres': typeof AppGenresRoute
  '/loans': typeof AppLoansRoute
  '/members': typeof AppMembersRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/books/$id': typeof AppBooksIdRoute
  '/members/$id': typeof AppMembersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/authors': typeof AppAuthorsRoute
  '/_app/book-copies': typeof AppBookCopiesRoute
  '/_app/books': typeof AppBooksRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/genres': typeof AppGenresRoute
  '/_app/loans': typeof AppLoansRoute
  '/_app/members': typeof AppMembersRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/books/$id': typeof AppBooksIdRoute
  '/_app/members/$id': typeof AppMembersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/authors'
    | '/book-copies'
    | '/books'
    | '/dashboard'
    | '/genres'
    | '/loans'
    | '/members'
    | '/notifications'
    | '/profile'
    | '/scan'
    | '/settings'
    | '/books/$id'
    | '/members/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/authors'
    | '/book-copies'
    | '/books'
    | '/dashboard'
    | '/genres'
    | '/loans'
    | '/members'
    | '/notifications'
    | '/profile'
    | '/scan'
    | '/settings'
    | '/books/$id'
    | '/members/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/authors'
    | '/_app/book-copies'
    | '/_app/books'
    | '/_app/dashboard'
    | '/_app/genres'
    | '/_app/loans'
    | '/_app/members'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/scan'
    | '/_app/settings'
    | '/_app/books/$id'
    | '/_app/members/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans': {
      id: '/_app/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/genres': {
      id: '/_app/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof AppGenresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books': {
      id: '/_app/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AppBooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/book-copies': {
      id: '/_app/book-copies'
      path: '/book-copies'
      fullPath: '/book-copies'
      preLoaderRoute: typeof AppBookCopiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/authors': {
      id: '/_app/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AppAuthorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/$id': {
      id: '/_app/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof AppMembersIdRouteImport
      parentRoute: typeof AppMembersRoute
    }
    '/_app/books/$id': {
      id: '/_app/books/$id'
      path: '/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof AppBooksIdRouteImport
      parentRoute: typeof AppBooksRoute
    }
  }
}

interface AppBooksRouteChildren {
  AppBooksIdRoute: typeof AppBooksIdRoute
}

const AppBooksRouteChildren: AppBooksRouteChildren = {
  AppBooksIdRoute: AppBooksIdRoute,
}

const AppBooksRouteWithChildren = AppBooksRoute._addFileChildren(
  AppBooksRouteChildren,
)

interface AppMembersRouteChildren {
  AppMembersIdRoute: typeof AppMembersIdRoute
}

const AppMembersRouteChildren: AppMembersRouteChildren = {
  AppMembersIdRoute: AppMembersIdRoute,
}

const AppMembersRouteWithChildren = AppMembersRoute._addFileChildren(
  AppMembersRouteChildren,
)

interface AppRouteChildren {
  AppAuthorsRoute: typeof AppAuthorsRoute
  AppBookCopiesRoute: typeof AppBookCopiesRoute
  AppBooksRoute: typeof AppBooksRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppGenresRoute: typeof AppGenresRoute
  AppLoansRoute: typeof AppLoansRoute
  AppMembersRoute: typeof AppMembersRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthorsRoute: AppAuthorsRoute,
  AppBookCopiesRoute: AppBookCopiesRoute,
  AppBooksRoute: AppBooksRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppGenresRoute: AppGenresRoute,
  AppLoansRoute: AppLoansRoute,
  AppMembersRoute: AppMembersRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
